# Generated by Django 2.2.14 on 2021-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Teclados'), ('M', 'Mouses'), ('G', 'Gabinetes')], max_length=2),
        ),
    ]
